cv design
mazharul/mazharul.github.com pull request #1
Opened 2023-04-14 04:46 UTC by Ziaurrahaman7

2023-04-14 08:20 UTC, mazharul commented
Hey - Add in a redirect rule for netlify redirect to redirect the content you have here to `domain.com/cv`

Here is a detail of how to do it: https://docs.netlify.com/routing/redirects/

2023-04-14 08:22 UTC, mazharul commented
Why did you edit the current index page? Commit your code to a new page. Name it `cv.html`

2023-04-14 08:22 UTC, mazharul commented
Don't change existing files.

2023-04-14 08:32 UTC, Ziaurrahaman7 commented
can i push index.html file rename with cv.html. are you want it ?

2023-04-14 08:37 UTC, mazharul commented
Revert back index.html file. Add your changes to cv.html file and push your commit. I will review the changes then.

2023-04-14 08:40 UTC, mazharul commented
Also - Don't forget to add the redirect rules. I have given you the documentation above.

2023-04-14 08:47 UTC, mazharul requested changes
Revert the index file back
Add redirect rule for netlify. See comments for documentation 
Make the page responsive.

2023-04-14 08:47 UTC, mazharul commented on index.html
Revert the file back.

2023-04-14 08:47 UTC, mazharul requested changes
Revert the index file back
Add redirect rule for netlify. See comments for documentation 
Make the page responsive.

2023-04-14 09:27 UTC, Ziaurrahaman7 commented
Redirect file added

2023-04-14 11:00 UTC, mazharul commented
Your build is failing - fix the redirect rule.

2023-04-14 11:02 UTC, mazharul requested changes
index.html file is still not reverted. Change back the index.html file - discard your changes to that file. 
Fix the redirect rule.
I can only validate your responsive page once the above are fixed.

2023-04-15 08:55 UTC, mazharul requested changes
Hey - not sure if you aren't getting it or if I am conveying it wrongly. 

- Revert back the content of index.html file to the original content.

2023-04-16 06:24 UTC, Ziaurrahaman7 commented
i did not found any revert option and it does not  merged

2023-04-17 00:25 UTC, mazharul requested changes

2023-04-17 00:25 UTC, mazharul commented on cv.html
> +      <h1 class="text-3xl">WORK EXPERIENCE</h1>
Remove this duplicated work experience :)

2023-04-17 00:25 UTC, mazharul commented on cv.html
> +      <h1 class="text-3xl">WORK EXPERIENCE</h1>
This is also duplicated.

2023-06-08 01:06 UTC, mazharul approved these changes

2023-06-08 01:07 UTC, merged